version: "3.9"

networks:
  toto:

services:
  nginx:
    build:
      context: .
      # context: ../firstContainer/lotoFlo
      dockerfile: docker/nginx.dockerfile
    image: nginx:stable
    ports:
      - "8098:80"
    volumes:
      - ./:/var/www/html
      # - ../firstContainer/lotoFlo:/var/www/html/
    links:
      - fpm
    networks:
      - toto

  fpm:
    build:
      context: .
      # context: ../firstContainer/lotoFlo
      dockerfile: docker/fpm.dockerfile
    volumes:
      - ./:/var/www/html
      # - ../firstContainer/lotoFlo:/var/www/html/
    networks:
      - toto

    environment:
      DATABASE_URL: mysql://root_ext:1234@172.29.177.67:3306/loto

  